
on:
  push:
    branches:           
      - master
jobs:
  FTP-Deploy-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master                   
      - name: FTP-Deploy-Action - develop
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: ./
          REMOTE_DIR: "/home/users/1/nisor/web/heteml-git_test/master"
          METHOD: sftp
          PORT: ${{ secrets.FTP_PORT }}
